mq:
  url: "![NRUbF3I8UK1nc0cad18xHEDD6V+g5smoqJTj/pjmH3LxsnwXyD+qLIpjq+1da5yhX7kA57UFbK9IRmxmFIiarZ31Sr58F7I6kZ5/ecQT/EYRTsxqcfb9pWTgVL7/zjc7zF5M1gs9zBvVKBetVD8fLeFpCzOXAkzTewJunaa8r7PoGv7IByImq8eBgfvt5Iyktby5IXZhFrwkfrfBXUn3gQ==]"
  clientid: "![N+ZugY+89xwB4aWgy8QXCl3WAL3+HDWG55xQNaSeKR1FEMSP/fJWhvT55SbP7RGm]"
  clientsecret: "![/6ZwN0GxrDn23iRCev4EcDwfscWAtv6sOJjPjspXaxpE5QW0dFR8nPeAfLAMesBe]"
